"""Make user_id in user_details unique

Revision ID: 127e6cbfcd09
Revises: b26067a334b1
Create Date: 2025-05-08 22:56:25.528534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '127e6cbfcd09'
down_revision = 'b26067a334b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_details', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_details', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
