"""Reset migration history

Revision ID: 456df15c00c0
Revises: 
Create Date: 2025-05-10 01:06:27.163079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '456df15c00c0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_quarter', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('push_token', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_column('push_token')
        batch_op.drop_column('target_quarter')

    # ### end Alembic commands ###
