"""Add image_urls to ProofSubmission

Revision ID: 63df2e73bc68
Revises: 456df15c00c0
Create Date: 2025-05-12 22:40:16.208752

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '63df2e73bc68'
down_revision = '456df15c00c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_column('push_token')

    with op.batch_alter_table('proof_submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_urls', postgresql.JSON(astext_type=sa.Text()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proof_submissions', schema=None) as batch_op:
        batch_op.drop_column('image_urls')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('push_token', sa.VARCHAR(length=255), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
