"""Add image_urls to ProofSubmission

Revision ID: 834565460634
Revises: 63df2e73bc68
Create Date: 2025-05-12 23:52:42.838246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '834565460634'
down_revision = '63df2e73bc68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('terms_accepted', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('terms_accepted')

    # ### end Alembic commands ###
